### ISSUE TITLE
node app.js出错

### ISSUE THREAD

**Issue by ifwangs** [Srar/AlipayF2F#5]
module.js:471
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/f2f/lib/aop.js:1:82)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by ifwangs** [comment]
搞定了。。。

**Comment by AkashiX** [comment]
解决方案？
